development:
  dialect: "sqlite3"
  database: {{env "GOPATH" }}/src/github.com/gobuffalo/toodo/toodo_development.sqlite

test:
  dialect: "sqlite3"
  database: {{env "GOPATH" }}/src/github.com/gobuffalo/toodo/toodo_test.sqlite

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/toodo_production?sslmode=disable"}}
