development:
  dialect: "sqlite3"
  database: {{env "GOPATH" }}/src/github.com/gobuffalo/toodo/toodo_development.sqlite

test:
  dialect: "sqlite3"
  database: {{env "GOPATH" }}/src/github.com/gobuffalo/toodo/toodo_test.sqlite

production:
  dialect: "sqlite3"
  database: {{env "GOPATH" }}/src/github.com/gobuffalo/toodo/toodo_production.sqlite